### ISSUE TITLE
Error with conditional code

### ISSUE THREAD

**Issue by sletz** [paolomarrone/Zampogna#4]
When building the `decimator` test, I get:

```
Zampogna/src/output_generation.js:117
				let bb = block.if_owners.at(-1)
				                         ^
TypeError: block.if_owners.at is not a function
    at convertBlock (/Users/letz/Developpements/Ciaramella/Zampogna/src/output_generation.js:117:30)
    at /Users/letz/Developpements/Ciaramella/Zampogna/src/output_generation.js:60:29
    at Array.forEach (<anonymous>)
    at Object.convert (/Users/letz/Developpements/Ciaramella/Zampogna/src/output_generation.js:60:12)
    at Object.compile (/Users/letz/Developpements/Ciaramella/Zampogna/src/zampogna.js:58:40)
    at /Users/letz/Developpements/Ciaramella/Zampogna/src/zampogna-cli.js:68:23
    at Object.<anonymous> (/Users/letz/Developpements/Ciaramella/Zampogna/src/zampogna-cli.js:74:2)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

Same kind of issue with `ifelseNormalize` and `saw_generator` examples.

**Comment by paolomarrone** [comment]
Hello and thanks,
you probably just need an higher version of node or browser.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
You need node version >= 16.6.0 or firefox version >= 90 or chrome version >= 92.
I probably should write these requirements in the README.

Let me know if it works.

**Comment by sletz** [comment]
Yes working now, thanks.
